version: '3.8'

services:
  Gro-Fresh:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: securepassword123
      DB_NAME: vendorsnearyou
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: vendorsnearyou
      MYSQL_USER: app_user
      MYSQL_PASSWORD: securepassword123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
